# MobileNet V1 model architecture

# [num of out filter, kernel_size, stride]

model_architecture : [
  [[32, 3, 1], [64, 1, 1]],
  [[64, 3, 2], [128, 1, 1]],
  [[128, 3, 1], [128, 1, 1]],
  [[128, 3, 2], [256, 1, 1]],
  [[256, 3, 1], [256, 1, 1]],
  [[256, 3, 2], [512, 1, 1]],
  [5, [512, 3, 1], [512, 1, 1]],
  [[512, 3, 2], [1024, 1, 1]], 
]