# t, c, n, s
# expansion, channel, repeat, stride

model_architecture : [
# bottleneck
  [1, 16, 1, 1],
  [6, 24, 2, 2],
  [6, 32, 3, 2],
  [6, 64, 4, 2],
  [6, 96, 3, 1],
  [6, 160, 3, 2],
  [6, 320, 1, 1],
]