model_architecture : [
  # num_of_out_filter, kernel_size, stride, padding
  # CSP Residual block, num_of_repeat
  [32, 3, 1, 1],
  [64, 3, 2, 1],
  ["B", 1],
  [128, 3, 2, 1],
  ["B", 2],
  [256, 3, 2, 1],
  ["B", 8],
  [512, 3, 2, 1],
  ["B", 8],
  [1024, 3, 2, 1],
  ["B", 4]
]